name: Gerar APK e Atualizar Versao no Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Compilar APK
      run: ./gradlew assembleDebug --no-daemon -Pksp.use.intellij.api=false -Pksp.incremental=false

    - name: Preparar Arquivos para Deploy
      run: |
        mkdir deploy_folder
        # Copia o APK gerado
        cp app/build/outputs/apk/debug/app-debug.apk deploy_folder/app-release.apk
        
        # Obtém o versionCode atual do arquivo version.properties
        VERSION_CODE=$(grep 'VERSION_CODE' app/version.properties | cut -d'=' -f2)
        
        # Cria o arquivo version.json para o aplicativo ler
        echo "{\"latestVersion\": $VERSION_CODE}" > deploy_folder/version.json
        
        echo "Versão $VERSION_CODE preparada para deploy."

    - name: Publicar no GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: deploy_folder
        branch: gh-pages
